/** Indian cities offered in the onboarding location picker, "City, State". */
export const INDIAN_CITIES = [
  'Agartala, Tripura',
  'Agra, Uttar Pradesh',
  'Ahmedabad, Gujarat',
  'Aizawl, Mizoram',
  'Ajmer, Rajasthan',
  'Aligarh, Uttar Pradesh',
  'Allahabad, Uttar Pradesh',
  'Amravati, Maharashtra',
  'Amritsar, Punjab',
  'Aurangabad, Maharashtra',
  'Bareilly, Uttar Pradesh',
  'Belgaum, Karnataka',
  'Bengaluru, Karnataka',
  'Bhavnagar, Gujarat',
  'Bhilai, Chhattisgarh',
  'Bhopal, Madhya Pradesh',
  'Bhubaneswar, Odisha',
  'Bikaner, Rajasthan',
  'Bilaspur, Chhattisgarh',
  'Chandigarh',
  'Chennai, Tamil Nadu',
  'Coimbatore, Tamil Nadu',
  'Cuttack, Odisha',
  'Dehradun, Uttarakhand',
  'Delhi',
  'Dhanbad, Jharkhand',
  'Dharamshala, Himachal Pradesh',
  'Durgapur, West Bengal',
  'Erode, Tamil Nadu',
  'Faridabad, Haryana',
  'Gandhinagar, Gujarat',
  'Gangtok, Sikkim',
  'Gaya, Bihar',
  'Ghaziabad, Uttar Pradesh',
  'Goa, Goa',
  'Gorakhpur, Uttar Pradesh',
  'Guntur, Andhra Pradesh',
  'Gurugram, Haryana',
  'Guwahati, Assam',
  'Gwalior, Madhya Pradesh',
  'Haridwar, Uttarakhand',
  'Hubli, Karnataka',
  'Hyderabad, Telangana',
  'Imphal, Manipur',
  'Indore, Madhya Pradesh',
  'Itanagar, Arunachal Pradesh',
  'Jabalpur, Madhya Pradesh',
  'Jaipur, Rajasthan',
  'Jalandhar, Punjab',
  'Jammu, Jammu & Kashmir',
  'Jamnagar, Gujarat',
  'Jamshedpur, Jharkhand',
  'Jodhpur, Rajasthan',
  'Kakinada, Andhra Pradesh',
  'Kanpur, Uttar Pradesh',
  'Kochi, Kerala',
  'Kohima, Nagaland',
  'Kolhapur, Maharashtra',
  'Kolkata, West Bengal',
  'Kollam, Kerala',
  'Kota, Rajasthan',
  'Kozhikode, Kerala',
  'Lucknow, Uttar Pradesh',
  'Ludhiana, Punjab',
  'Madurai, Tamil Nadu',
  'Mangaluru, Karnataka',
  'Mathura, Uttar Pradesh',
  'Meerut, Uttar Pradesh',
  'Mumbai, Maharashtra',
  'Mysuru, Karnataka',
  'Nagpur, Maharashtra',
  'Nanded, Maharashtra',
  'Nashik, Maharashtra',
  'Navi Mumbai, Maharashtra',
  'Nellore, Andhra Pradesh',
  'Noida, Uttar Pradesh',
  'Panaji, Goa',
  'Patiala, Punjab',
  'Patna, Bihar',
  'Puducherry',
  'Pune, Maharashtra',
  'Raipur, Chhattisgarh',
  'Rajkot, Gujarat',
  'Ranchi, Jharkhand',
  'Rourkela, Odisha',
  'Salem, Tamil Nadu',
  'Sangli, Maharashtra',
  'Shillong, Meghalaya',
  'Shimla, Himachal Pradesh',
  'Siliguri, West Bengal',
  'Solapur, Maharashtra',
  'Srinagar, Jammu & Kashmir',
  'Surat, Gujarat',
  'Thane, Maharashtra',
  'Thiruvananthapuram, Kerala',
  'Thrissur, Kerala',
  'Tiruchirappalli, Tamil Nadu',
  'Tirunelveli, Tamil Nadu',
  'Tirupati, Andhra Pradesh',
  'Udaipur, Rajasthan',
  'Ujjain, Madhya Pradesh',
  'Vadodara, Gujarat',
  'Varanasi, Uttar Pradesh',
  'Vasai-Virar, Maharashtra',
  'Vijayawada, Andhra Pradesh',
  'Visakhapatnam, Andhra Pradesh',
  'Warangal, Telangana',
];
