import React,{useEffect,useState}from'react';
import{Link,useNavigate,useLocation}from'react-router-dom';
import{sendPasswordResetEmail,signInWithEmailAndPassword,signOut}from'firebase/auth';
import{auth}from'../../firebase';import{useAuth,type UserRole}from'../../context/AuthContext';import'../AuthPages.css';
interface LoginPageProps{loginRole?:UserRole}
const path=(role:UserRole)=>role==='vendor'?'/vendor-onboarding':role==='customer'?'/buyer-dashboard':role==='admin'?'/admin-dashboard':'/user-dashboard';
const LoginPage:React.FC<LoginPageProps>=()=>{const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');const[info,setInfo]=useState('');const[busy,setBusy]=useState(false);const navigate=useNavigate();const location=useLocation();const{currentUser,userRole,loading,getUserRole}=useAuth();
const forceLogin=(location.state as {forceLogin?:boolean})?.forceLogin;
useEffect(()=>{if(!loading&&currentUser&&userRole&&!forceLogin)navigate(path(userRole),{replace:true})},[loading,currentUser,userRole,navigate,forceLogin]);
const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');setBusy(true);try{const user=(await signInWithEmailAndPassword(auth,email.trim().toLowerCase(),password)).user;const cachedRole=localStorage.getItem(`user_role_${user.uid}`) as UserRole| null;const validRoles=['admin','user','vendor','customer'] as const; if(cachedRole&&validRoles.includes(cachedRole)){setInfo('Welcome back! Taking you to your dashboard…');navigate(path(cachedRole),{replace:true});return;}const role=await getUserRole(user);if(!role){await signOut(auth);setError('This account has no assigned role. Please register first.');return}setInfo('Welcome back! Taking you to your dashboard…');navigate(path(role),{replace:true});}catch(err:any){setError(err.code==='auth/invalid-credential'?'Incorrect email or password.':err.message||'Unable to sign in.')}finally{setBusy(false)}};
const forgot=async()=>{if(!email){setError('Enter your email address first.');return}try{await sendPasswordResetEmail(auth,email.trim());setInfo('Password reset link sent.')}catch(err:any){setError(err.message||'Unable to send reset link.')}};
return <main className="auth-page"><section className="auth-card"><div className="auth-icon">✉</div><h1 className="auth-title">Welcome Back</h1><p className="auth-subtitle">Sign in to your Vendora account.</p><form className="auth-form" onSubmit={submit}><input className="auth-input" type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><div><div className="auth-row"><label>Password</label><button className="auth-link" type="button" onClick={forgot}>Forgot password?</button></div><input className="auth-input" type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={6}/></div>{error&&<p className="auth-message auth-error">{error}</p>}{info&&<p className="auth-message auth-success">{info}</p>}<button className="auth-primary" disabled={busy}>{busy?'Signing in…':'Login'}</button></form><p className="auth-note">Don’t have an account? <Link className="auth-link" to="/register">Register</Link></p></section></main>};
export default LoginPage;
